baseURL = 'https://maplegrove.top/'
languageCode = 'zh-cn'
title = '休息的风'
theme = 'ananke'

DefaultContentLanguage = "zh"

SectionPagesMenu = "main"
Paginate = 3 
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh]
    title = "休息的风"
    weight = 1
    contentDir = "content/zh"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "vine"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # 设置背景色
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/VineFiner"
